name: SlackSendMessage
description: 'Notifies slack of the success or failure of the suite'
inputs:
  message:
    description: "Message to send to the Slack webhook notification channel"
    required: true
  url:
    description: "Webhook URL to send the Slack notification to"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        URL: ${{ inputs.url }}
        MESSAGE: ${{ inputs.message }}
      run: |
        JSON="{'message': '$MESSAGE'}"
        curl -X POST -H 'Content-Type: application/json' --data "${JSON}" "$(printf "$URL" | tr -d "\n")"