# we support merge request workflow only
include:
  - local: '.gitlab/ci/*.yml'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_SERVER_HOST == "gitlab.com"'
      variables:
        PUSH_CUSTOM_IMAGE: "true"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_SERVER_HOST == "ops.gitlab.net" || $CI_SERVER_HOST == "dev.gitlab.org")'
      variables:
        PUSH_CUSTOM_IMAGE: "true"
        BASE_BUILD_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE

default:
  interruptible: true
  image: ${BASE_BUILD_REGISTRY_IMAGE}/debian-bullseye-slim:docker-${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  tags:
    - gitlab-org-docker

stages:
  - custom
  - gitlab
  - gitlab-assets
  - gitlab-review-app
  - workhorse
  - gitaly
  - automation

variables:
  DOCKER_HOST: tcp://docker:2375
  BASE_BUILD_REGISTRY_IMAGE: registry.gitlab.com/gitlab-org/gitlab-build-images
  DOCKER_VERSION: "23.0.1"

dont-interrupt-me:
  extends: .dont-interrupt-me

cache-chrome-chromium:
  extends: .cache-google-chrome
