.check:
  extends:
    - .ci_function
    - .ci-job
  interruptible: true
  stage: .pre
  allow_failure: true
  rules:
    - if: $DEPLOY_TAG
      when: never
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_NAME =~ /^.*\/.*$/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

.check alerts:
  extends: .check
  stage: .pre
  allow_failure: false
  script:
    - run_ci

.helm check:
  extends:
    - .ci_function
    - .ci-job
  interruptible: true
  stage: build
  tags: [helm-check]
  script:
    - run_ci
  variables:
    GIT_DEPTH: "3"
  except:
    refs:
      - tags
    variables:
      - $CI_PROJECT_PATH == "marketplace/go/marketplace-api"

.validate config:
  stage: build
  extends: 
    - .ci_function
    - .ci-job
  interruptible: true
  only:
    variables:
      - $DEPLOY_CONFIG == "yes" # from 0.0.4
      - $VALIDATE_CONFIG == "yes"
  script:
    - validate_config
  except:
    refs:
      - tags
  variables:
    GIT_DEPTH: "3"

.check jira flow:
  extends:
    - .ci_function
    - .ci-job
  interruptible: true
  stage: .pre
  allow_failure: true
  script:
    - run_ci

.warning:
  extends:
    - .ci_function
    - .ci-job
  interruptible: true
  stage: .pre
  allow_failure: true
  script:
    - run_ci

.error:
  extends:
    - .ci_function
    - .ci-job
  interruptible: true
  stage: .pre
  allow_failure: false
  script:
    - run_ci
