.keycloak:stg:
  extends: .keycloak
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_NAME =~ /^((release|hotfix)\/.+|release|stable|trunk|master)$/'
      exists:
        - .o3/keycloak.yaml
      when: manual


.keycloak:dev:
  extends: .keycloak
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_REF_NAME !~ /^((release|hotfix)\/.+|release|stable|trunk)$/'
      exists:
        - .o3/keycloak.yaml
      when: manual

.keycloak:prod:
  extends: .keycloak
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_NAME !~ /^.*\/.*$/'
      exists:
        - .o3/keycloak.yaml
      when: manual
