---
source: https://github.com/aws-samples/serverless-webapp-mono-repo-ci-cd-java/blob/master/.github/workflows/build-backend-infra.yml
tags: ['github action', 'merge', 'build', 'automerge', 'dependabot, 'github-script']
---

name: Build Backend Infra

on:
  pull_request:
    branches:
      - master
    paths:
      - 'java-app-backend/**'
  push:
    branches:
      - master
    paths:
      - 'java-app-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        java: [8, 11.0.x]
    name: Java ${{ matrix.java }}
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java-version }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        working-directory: ./java-app-backend/BackendFunction
        run: mvn -B package --file pom.xml

  auto-merge:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
          github-token: ${{ secrets.AUTOMERGE }}