---
source:
- https://github.com/heinrichreimer/action-github-changelog-generator
- https://renehernandez.io/essays/2020/09/23/automate-changelog-and-releases-creation-in-github
tags: ['github action', 'changelog']
---

name: CI

on: push

jobs:
  build:
    name: "✏️ Changelog generation"
    runs-on: ubuntu-18.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "✏️ Generate full changelog"
        id: ch
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          headerLabel: "# 📑 Changelog"
          breakingLabel: '### 💥 Breaking'
          enhancementLabel: '### 🚀 Enhancements'
          bugsLabel: '### 🐛 Bug fixes'
          deprecatedLabel: '### ⚠️ Deprecations'
          removedLabel: '### 🔥 Removals'
          securityLabel: '### 🛡️ Security'
          issuesLabel: '### 📁 Other issues'
          prLabel: '### 📁 Other pull requests'
          addSections: '{"documentation":{"prefix":"### 📖 Documentation","labels":["documentation"]},"tests":{"prefix":"### ✅ Testing","labels":["tests"]}}'
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          author: true
          unreleased: true
          compareLink: true
          stripGeneratorNotice: true
          verbose: true
      - name: "🖨️ Print changelog to console"
        run: cat CHANGELOG.md
      - name: "📤 Upload changelog"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: "Changelog"
          path: CHANGELOG.md

    - name: check outputs
      run: |
        echo "Changelog - ${{ steps.ch.outputs.changelog }}"
