---
source:
- https://github.com/micnncim/action-label-syncer
tags: ['github action', 'sync', 'labeller', 'different repo']
---

name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - path/to/manifest/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: path/to/manifest/labels.yml
          repository: myother/repository
          token: ${{ secrets.PERSONAL_TOKEN }}
          