---
source:
- https://github.com/sindresorhus/refined-github/blob/main/.github/workflows/labeler.yml
- https://github.com/fregante/title-to-labels-action
tags: ['github action', 'issues', 'labeller']
---

name: Labeler

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
