---
source:
- https://github.com/DeFiCh/oss-governance-bot
- https://github.com/DeFiCh/ain/blob/master/.github/workflows/oss-governance-bot.yml
tags: ['github action', 'release build', 'sha']
---

name: OSS

on:
  pull_request_target:
    branches: [ master, main ]
    types: [ synchronize, opened, labeled, unlabeled ]
  issues:
    types: [ opened, labeled, unlabeled ]
  issue_comment:
    types: [ created ]

jobs:
  main:
    name: Governance
    runs-on: ubuntu-latest
    steps:
      - uses: DeFiCh/oss-governance-bot@v2
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

