---
source:
- https://github.com/lincolnloop/ecs-task/blob/master/.github/workflows/test.yml
- https://github.com/aws/aws-cli/blob/develop/.github/workflows/run-tests.yml
tags: ['github action', 'python', 'fail-fast']
---

name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        # todo: test 2.7 (can't use flit)
        # python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade flit
        flit install --extras=test
    - name: Test with pytest
      run: |
        pytest -v --cov=ecs_task --cov-report=term tests.py
    - name: Run tests
      run: python scripts/ci/run-tests
    - name: Run checks
      run: python scripts/ci/run-check