# source:
# - https://github.com/search?o=zaproxy&q=zaproxy%2Faction-baseline+path%3A.github%2Fworkflows+language%3AYAML&s=&type=Code
# - https://github.com/fabasoad/yaml-json-xml-converter-action/blob/main/.github/workflows/security-tests.yml
# tags: ['github action', 'owasp', 'security', 'zaproxy', audit, baseline]

---
name: Security Tests

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  push:
    branches:
      - main
      - 'bugfix/**'
      - 'feature/**'
  schedule:
    - cron: '37 10 * * 4'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'