---
source:
- https://github.com/technote-space/toc-generator#condition2
- https://github.com/ivankatliarchuk/.github
tags: ['github action', 'toc']
---

on:
  push:
    branches:
      - master # Push events on master branch
name: Table of Contents Generator
jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: "README.md"
          INCLUDE_LABELS: documentation
          CREATE_PR: true
          CHECK_ONLY_DEFAULT_BRANCH: true
