# source:
# - https://github.com/search?o=desc&q=release-drafter+path%3A.github%2Fworkflows+language%3AYAML&s=&type=Code
# - https://github.com/release-drafter/release-drafter/blob/master/.github/workflows/tests.yml
# tags: ['github action', 'release-drafter', 'yarn', 'node']

name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '13'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn lint --fix
      - run: yarn prettier
      - run: yarn build
      - name: correct vercel/ncc crlf output
        run: sed -i 's/\x0D$//' ./dist/index.js
      - run: .github/no-unstaged-files.sh
